version: '3'

services:
  yapi-web:
    image: zhuowenli/yapi:latest
    container_name: yapi-web
    ports:
      - "3000:3000"
    environment:
      - YAPI_ADMIN_ACCOUNT=admin@docker.yapi
      - YAPI_ADMIN_PASSWORD=adm1n
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    # volumes:
    #   - ./vendors:/yapi/vendors
    links:
      - yapi-mongo
    restart: unless-stopped
    networks:                       # 加入指定网络
      - app-network

  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
    networks:                       # 加入指定网络
      - app-network

networks:  # 实现通信
  app-network:
    driver: bridge
